import type { Metadata } from "next"
import "./globals.css"

import { Inter as FontSans } from "next/font/google"

import { cn } from "@/lib/utils"
import SideBar from "@/components/side-bar"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-background min-h-screen font-sans antialiased", fontSans.variable)}>
        <div className="flex">
          <SideBar />
          {children}
        </div>
      </body>
    </html>
  )
}
