import type { Metadata } from "next"
import "./globals.css"
import { Inter as FontSans } from "next/font/google"

import { cn } from "@/lib/utils"
import SideBar from "@/components/side-bar"
import { Provider } from "@/components/provider"
import { Toaster } from "@/components/ui/toaster"
import { FloatingButton } from "@/components/floating-button"
import { auth } from "@/auth"
import { DevTools } from "@/components/DevTool"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  console.log("uesr session id ", session?.user?.id)
  return (
    <Provider>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable,
          )}>
          <div className="flex">
            <SideBar />
            {children}
          </div>
          {session !== null && session?.user ? <FloatingButton /> : null}
          <Toaster />
          <DevTools />
        </body>
      </html>
    </Provider>
  )
}
