import type { Metadata } from "next"
import "./globals.css"

import { Inter as FontSans } from "next/font/google"

import { cn } from "@/lib/utils"
import SideBar from "@/components/side-bar"
import { Provider } from "@/components/provider"
import { Toaster } from "@/components/ui/toaster"
import { FloatingButton } from "@/components/floating-button"
import { auth } from "@/auth"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth();
  return (
    <Provider>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable,
          )}>
          <div className="flex">
            <SideBar />
            <div className="flex px-5 min-h-screen flex-1 flex-col items-center justify-between">
              {children}
            </div>
          </div>
          {session !== null && session?.user ? (

            <FloatingButton />
          ) : null}
          <Toaster />
        </body>
      </html>
    </Provider>
  )
}
